services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conferencedb
  back-office-gateway:
    build:
      context: .
      dockerfile: back-office-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  conference-gateway:
    build:
      context: .
      dockerfile: conference-gateway/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db